// videoData.ts
export const videos = [
  { videoUrl: 'video26.mp4', title: 'Aaj To sunday hai yay yay ', username: 'sundayFood', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video1.mp4', title: 'When dragons are never caged', username: 'houseOfDragon', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video2.mp4', title: 'Aage kya Karna hai ?', username: 'kotaFactory', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video3.mp4', title: 'Cheezo ke peeche kyo bhagte ho?', username: 'khushRahaKar', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video4.mp4', title: 'I found My bestie childhood video', username: 'childhoodMemory', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video5.mp4', title: 'Mah Mah Mah ', username: 'aajkalKeBache', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video6.mp4', title: 'Mote hai to kya, artist hai', username: 'bodyArtist', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video7.mp4', title: 'Take a breath.... ', username: 'fullMotivation', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video8.mp4', title: 'All couple must spend time & enjoy ', username: 'enjoyWithLove', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video9.mp4', title: 'My Dream setup :)', username: 'codingHub', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video10.mp4', title: 'Artist live Out of the box ', username: 'artofThings', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video11.mp4', title: 'When Beatboxer friends meet ', username: 'BeatBoxers', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video12.mp4', title: 'Just say A A A and you are viral. ', username: 'khabyMusic', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video13.mp4', title: 'Pyaar mein jhagde chess ki trah', username: 'loveExplained', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video14.mp4', title: 'When Alan becker write an email', username: 'alanbecker', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video15.mp4', title: 'Cutest glummy smile', username: 'cutekids', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video16.mp4', title: 'A love song for goat ', username: 'animalLover', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video17.mp4', title: 'This song took my all oxyzen', username: 'realSingers', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video18.mp4', title: 'Learn what is emotional damage ', username: 'funLearning', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video19.mp4', title: 'Today I learn cook pasta but..', username: 'exploreLife', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video20.mp4', title: 'Being honest is matter for your loved one.', username: 'loveTips', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video21.mp4', title: 'Hey Siri, I am failed : (', username: 'siriAdvices', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video22.mp4', title: 'What the hack I just wacthed ? ', username: 'amazingThings', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video23.mp4', title: 'How to make Chatne-wala Kulfi ?', username: 'bestChef', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video24.mp4', title: 'I know I am slow but he ate all', username: 'foodies', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video25.mp4', title: 'Abhi bechara kuch to nahi banna', username: 'cuteBaatein', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video27.mp4', title: 'I know tum hoshiyaar ho but', username: 'kidsThinking', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video28.mp4', title: 'A geniune partner', username: 'realPartner', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video29.mp4', title: 'How to get slim without avoid my fav food.', username: 'siriTips', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video30.mp4', title: 'Mera Sapna pura hogya aaj', username: 'weirdThings', avatarUrl: '/avatar1.png' },
    { videoUrl: 'video31.mp4', title: 'In On At what the heck???', username: 'englishTips', avatarUrl: '/avatar2.png' },
    { videoUrl: 'video32.mp4', title: 'Imagine How powerful I wwould be..', username: 'amazingThings', avatarUrl: '/avatar1.png' },
 
  ];
  